let egw=[],relations=[],sermonSchema=null,bibleSource=null,bibleBooks=[],current=null;const bibleCache=new Map();
const fallbackHierarchy=[{level:1,label:'圣经',rule:'primary'},{level:2,label:'预言之灵原始资料',rule:'supporting_verified_source'},{level:3,label:'我的研究',rule:'user_authored'},{level:4,label:'AI整理',rule:'derived_only_never_quote_as_source'}];
const legacyIdMap={da29:'DA-29-SABBATH',ed29:'ED-29-SABBATH',cch47:'CCH-47-SABBATH','6t44':'6T-44-SABBATH',cihs:'CIHS-2300',ew:'EW-VISIONS',ev8:'EV-08-DISTINCTIVE'};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function norm(s){return String(s||'').trim().replace(/\s+/g,'').replace(/[：]/g,':').toLowerCase()}
async function loadData(){const st=document.getElementById('dataStatus');try{const urls=['./data/egw-index.json','./data/bible-egw-relations.json','./data/sermon-project-schema.json','./data/bible-source.json','./data/bible-books.json'];const rs=await Promise.all(urls.map(u=>fetch(u,{cache:'no-store'})));if(rs.some(r=>!r.ok))throw Error('data fetch failed');const [ej,rj,sj,bs,bm]=await Promise.all(rs.map(r=>r.json()));egw=ej.records||[];relations=rj.relations||[];sermonSchema=sj;bibleSource=bs;bibleBooks=bm.books||[];st.textContent=`圣经66卷 · 怀著 ${egw.length} · 关系 ${relations.length}`;st.className='status ok';migrateLegacy();renderHierarchy();renderProjectHome();renderBasket()}catch(e){console.error(e);if(st){st.textContent='资料加载失败';st.className='status bad'}sermonSchema={source_hierarchy:fallbackHierarchy};renderHierarchy()}}
function renderHierarchy(){const rows=sermonSchema?.source_hierarchy||fallbackHierarchy;const host=document.getElementById('sourceHierarchy');if(host)host.innerHTML=rows.map(x=>`<div class="layer"><b>${esc(x.level)}</b><div><strong>${esc(x.label)}</strong><p class="muted">${x.rule==='primary'?'圣经正文、上下文和相关经文。':x.rule==='supporting_verified_source'?'怀著精确出处与官方上下文。':x.rule==='user_authored'?'讲道人自己的研究笔记。':'只整理已核验资料，不冒充来源。'}</p></div></div>`).join('')}
function parseBibleRef(q){let n=norm(q);for(const [osis,full,short] of bibleBooks){for(const a of [full,short,osis]){const aa=norm(a);if(n.startsWith(aa)){let tail=n.slice(aa.length),m=tail.match(/^(\d+)(?::(\d+)(?:[-–](\d+))?)?$/);if(m)return{osis,full,short,chapter:+m[1],from:m[2]?+m[2]:null,to:m[3]?+m[3]:(m[2]?+m[2]:null)}}}}return null}
async function loadBibleBook(osis){if(bibleCache.has(osis))return bibleCache.get(osis);const cfg=bibleSource?.translations?.[bibleSource.default_translation];if(!cfg)throw Error('Bible source missing');const r=await fetch(cfg.base_url+osis+'.json');if(!r.ok)throw Error('Bible book fetch '+r.status);const j=await r.json();bibleCache.set(osis,j);return j}
function chapterFromBook(book,n){if(Array.isArray(book.chapters)){const c=book.chapters[n-1];return c?.verses||c||[]}return []}
async function biblePassage(ref){if(!ref)return null;const book=await loadBibleBook(ref.osis),verses=chapterFromBook(book,ref.chapter);let selected=verses;if(ref.from)selected=verses.filter(v=>Number(v.number??v.verse)>=ref.from&&Number(v.number??v.verse)<=ref.to);return{...ref,verses:selected}}
function relationFor(q){const n=norm(q);return relations.find(x=>[x.bible_ref,x.normalized,...(x.themes||[])].some(v=>v&&(n.includes(norm(v))||norm(v).includes(n))))||null}
function relatedEGW(q,rel){const ids=new Set(rel?.egw_ids||[]),terms=[q,...(rel?.themes||[]),...(rel?.related_bible||[])].map(norm);return egw.filter(e=>ids.has(e.id)||terms.some(t=>t&&[e.title_cn,e.title,e.book_code,e.chapter,e.locator,...(e.bible_refs||[]),...(e.topics||[])].map(norm).some(h=>h.includes(t)||t.includes(h))))}
function go(p){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(p)?.classList.add('active');document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));if(p==='library')renderLibrary();if(p==='projects')renderProjects();if(p==='basket')renderBasket()}
function quick(q){const h=document.getElementById('homeQ');if(h)h.value=q;runStudy('homeQ')}
async function runStudy(id){const input=document.getElementById(id),q=input?.value.trim();if(!q)return;go('study');const sq=document.getElementById('studyQ'),host=document.getElementById('studyResult');if(sq)sq.value=q;if(!host)return;host.innerHTML='<div class="empty">正在读取圣经与资料索引…</div>';const ref=parseBibleRef(q),rel=relationFor(q),hits=relatedEGW(q,rel);let h='';if(ref){try{const p=await biblePassage(ref);h+=`<div class="card"><div class="meta">第一层 · 圣经 · 和合本简体</div><h3>${esc(ref.full)} ${ref.chapter}${ref.from?':'+ref.from+(ref.to!==ref.from?'–'+ref.to:''):''}</h3>${p.verses.map(v=>`<div class="verse"><div class="verse-num">${esc(v.number??v.verse)}</div><div class="verse-text">${esc(v.text)}</div></div>`).join('')}<div class="actions"><button onclick="openBible('${ref.osis}',${ref.chapter})">阅读整章</button></div></div>`}catch(e){h+=`<div class="card"><div class="meta">第一层 · 圣经</div><p>正文暂时读取失败，但仍继续查询本地关系索引。</p></div>`}}else if(rel)h+=`<div class="card"><div class="meta">第一层 · 圣经关系索引</div><h3>${esc(rel.bible_ref)}</h3></div>`;else h+=`<div class="card"><div class="meta">研究主题</div><h3>${esc(q)}</h3></div>`;if(rel)h+=`<div class="source"><b>相关经文</b><br>${(rel.related_bible||[]).map(esc).join(' · ')||'暂无'}</div>`;h+=`<div class="section-head" style="margin-top:18px"><h2>预言之灵相关资料</h2><span>${hits.length} 条</span></div>`;if(!hits.length)h+='<div class="empty">当前怀著索引暂无精确结果；不会用 AI 猜测冒充原文。</div>';hits.forEach(e=>h+=egwCard(e));host.innerHTML=h}
async function openBible(osis,chapter){const b=bibleBooks.find(x=>x[0]===osis);try{const p=await biblePassage({osis,full:b?.[1]||osis,short:b?.[2]||'',chapter,from:null,to:null});current=null;readerAction.style.display='none';rmeta.textContent='第一层 · 圣经 · 和合本简体';rtitle.textContent=`${p.full} ${chapter}章`;rbody.innerHTML=p.verses.map(v=>`<div class="verse"><div class="verse-num">${esc(v.number??v.verse)}</div><div class="verse-text">${esc(v.text)}</div></div>`).join('');rtools.innerHTML='';reader.style.display='block'}catch(e){alert('这一章暂时读取失败')}}
function egwCard(e){return `<div class="result"><div class="meta">第二层 · 预言之灵原始资料定位</div><h3>《${esc(e.title_cn||e.title)}》 · ${esc(e.chapter||'')}</h3><div class="source"><b>${esc(e.book_code||'')} · ${esc(e.locator||'')}</b><br>相关经文：${(e.bible_refs||[]).map(esc).join(' · ')}</div><p style="margin-top:9px"><b>经光研究摘要：</b>${esc(String(e.summary||'').replace('研究摘要：',''))}</p><div class="actions"><button class="primary" onclick="openEGW('${esc(e.id)}')">查看出处</button><button onclick="addBasket('${esc(e.id)}')">＋材料篮</button></div></div>`}
function openEGW(id){const e=egw.find(x=>x.id===id);if(!e)return;current=e;readerAction.style.display='block';rmeta.textContent=`预言之灵 · ${e.book_code||''} · ${e.locator||''}`;rtitle.textContent=`《${e.title_cn||e.title}》 ${e.chapter||''}`;rbody.innerHTML=`<p>${esc(e.summary||'')}</p><p><b>涉及经文</b><br>${(e.bible_refs||[]).map(esc).join(' · ')}</p>`;rtools.innerHTML=`<div class="card"><div class="actions"><button class="primary" onclick="window.open('${esc(e.source_url||'')}','_blank')">阅读官方原始上下文 ↗</button></div></div>`;reader.style.display='block'}
function closeReader(){reader.style.display='none'}
function addCurrent(){if(current)addBasket(current.id)}
function getBasket(){try{return JSON.parse(localStorage.getItem('jg_v10_basket')||'[]')}catch{return[]}}
function migrateLegacy(){localStorage.setItem('jg_v10_basket',JSON.stringify([...new Set(getBasket().map(x=>legacyIdMap[x]||x))]))}
function addBasket(id){let a=getBasket();if(!a.includes(id))a.push(id);localStorage.setItem('jg_v10_basket',JSON.stringify(a));renderBasket();alert('已加入材料篮')}
function removeBasket(id){localStorage.setItem('jg_v10_basket',JSON.stringify(getBasket().filter(x=>x!==id)));renderBasket()}
function renderBasket(){const es=getBasket().map(id=>egw.find(x=>x.id===id)).filter(Boolean);if(document.getElementById('basketCount'))basketCount.textContent=`${es.length} 条`;if(document.getElementById('basketList'))basketList.innerHTML=es.length?es.map(e=>`<div class="result basket"><div class="meta">${esc(e.book_code)} · ${esc(e.locator)}</div><h3>《${esc(e.title_cn||e.title)}》</h3><div class="actions"><button onclick="openEGW('${esc(e.id)}')">核对出处</button><button onclick="removeBasket('${esc(e.id)}')">移除</button></div></div>`).join(''):'<div class="empty">材料篮还是空的。</div>'}
function getProjects(){try{return JSON.parse(localStorage.getItem('jg_v10_projects')||'[]')}catch{return[]}}
function saveProjects(a){localStorage.setItem('jg_v10_projects',JSON.stringify(a));renderProjects();renderProjectHome()}
function normalizeProject(p){p.status=p.status==='研究中'?'researching':(p.status||'researching');p.research_notes=p.research_notes??p.notes??'';p.materials=p.materials||[];p.audience=p.audience||'普通信徒';p.duration_minutes=Number(p.duration_minutes||30);p.updated_at=p.updated_at||new Date(p.updated||Date.now()).toISOString();return p}
function snapshotMaterial(id){const e=egw.find(x=>x.id===id);return e?{id:`mat-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,type:'egw',source_id:e.id,label:`《${e.title_cn||e.title}》 ${e.chapter||''}`,locator:e.locator||null,verified:false,note:'',source_url:e.source_url||'',bible_refs:e.bible_refs||[]}:null}
function createProject(){const title=document.getElementById('newProjectTitle'),aud=document.getElementById('newProjectAudience'),dur=document.getElementById('newProjectDuration');const t=title?.value.trim();if(!t)return;const now=new Date().toISOString(),a=getProjects();a.unshift({id:`sermon-${Date.now()}`,title:t,status:'researching',audience:aud?.value||'普通信徒',duration_minutes:+(dur?.value||30),core_bible_refs:[],materials:[],outline:[],application:'',appeal:'',research_notes:'',created_at:now,updated_at:now});saveProjects(a);title.value=''}
function statusLabel(s){return({researching:'研究中',outlining:'整理结构',ready:'可讲',archived:'已归档'})[s]||s}
function renderProjects(){const a=getProjects().map(normalizeProject);if(!document.getElementById('projectsList'))return;projectsList.innerHTML=a.length?a.map(p=>`<div class="result project"><div class="meta">${statusLabel(p.status)} · ${new Date(p.updated_at).toLocaleDateString()}</div><h3>${esc(p.title)}</h3><p>${esc(p.audience)} · ${p.duration_minutes}分钟 · 材料 ${p.materials.length} 条</p><div class="field"><label>我的研究笔记</label><textarea onchange="updateProject('${p.id}',this.value)">${esc(p.research_notes)}</textarea></div><div class="actions"><button onclick="attachBasket('${p.id}')">把材料篮加入项目</button><button onclick="deleteProject('${p.id}')">删除</button></div></div>`).join(''):'<div class="empty">还没有讲章项目。</div>'}
function updateProject(id,v){let a=getProjects().map(normalizeProject),p=a.find(x=>String(x.id)===String(id));if(!p)return;p.research_notes=v;p.updated_at=new Date().toISOString();saveProjects(a)}
function attachBasket(id){let a=getProjects().map(normalizeProject),p=a.find(x=>String(x.id)===String(id));if(!p)return;let seen=new Set(p.materials.map(m=>m.source_id));getBasket().forEach(x=>{if(!seen.has(x)){let m=snapshotMaterial(x);if(m)p.materials.push(m)}});p.updated_at=new Date().toISOString();saveProjects(a)}
function deleteProject(id){saveProjects(getProjects().filter(x=>String(x.id)!==String(id)))}
function renderProjectHome(){const a=getProjects().map(normalizeProject);if(document.getElementById('projectCount'))projectCount.textContent=`${a.length} 个项目`;if(document.getElementById('projectHome'))projectHome.innerHTML=a.length?a.slice(0,3).map(p=>`<div class="result project"><div class="meta">${statusLabel(p.status)}</div><h3>${esc(p.title)}</h3><p>${p.materials.length} 条材料 · ${p.research_notes?'已有研究笔记':'尚未写笔记'}</p><div class="actions"><button onclick="go('projects')">继续备讲</button></div></div>`).join(''):'<div class="card"><p>建立第一个讲章项目后，会在这里继续。</p><div class="actions"><button onclick="go('projects')">建立讲章项目</button></div></div>'}
function renderLibrary(){if(document.getElementById('libraryCount'))libraryCount.textContent=`${egw.length} 条`;if(document.getElementById('libraryList'))libraryList.innerHTML=egw.map(egwCard).join('')}
loadData();