'use strict';
const S={egw:[],egwBooks:[],rels:[],books:[],source:null,cache:new Map(),filter:'all',shelf:'bible'};
const K={basket:'jg_v10_basket',projects:'jg_v10_projects',recent:'jg_v10_recent',reading:'jg_v10_reading',favorites:'jg_v10_favorites',font:'jg_v10_bible_font',theme:'jg_v10_theme',position:'jg_v10_reading_position',studyState:'jg_v10_study_state'};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLowerCase().replace(/[\s《》〈〉“”"'，。！？；、·_]/g,'').replace(/：/g,':').replace(/[–—]/g,'-');
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1600)}
function debounce(fn,wait=250){let t=0,lastArgs=[];const wrapped=(...args)=>{lastArgs=args;clearTimeout(t);t=setTimeout(()=>{t=0;fn(...lastArgs)},wait)};wrapped.cancel=()=>{clearTimeout(t);t=0};return wrapped}
const readStudyState=()=>{try{return JSON.parse(sessionStorage.getItem(K.studyState)||'null')}catch{return null}};
const writeStudyState=v=>{try{sessionStorage.setItem(K.studyState,JSON.stringify(v))}catch{}};
function saveStudyState(extra={}){const host=$('studyResults'),input=$('studyQ');writeStudyState({query:input?.value||'',filter:S.filter,scrollY:window.scrollY||0,results:host?.innerHTML||'',...extra})}
function restoreStudyState(){const saved=readStudyState();if(!saved)return false;if(typeof saved.query==='string'&&$('studyQ'))$('studyQ').value=saved.query;if(saved.filter){S.filter=saved.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===S.filter))}if(typeof saved.results==='string'&&saved.results&&$('studyResults')){$('studyResults').innerHTML=saved.results;filter();requestAnimationFrame(()=>scrollTo(0,Math.max(0,+saved.scrollY||0)));return true}return false}
function page(id,opt={}){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='home')home();if(id==='library')library();if(id==='favorites')renderFavorites();if(id==='projects')renderProjects();if(id==='basket')renderBasket();const restored=id==='study'&&restoreStudyState();if(!opt.keepScroll&&(!restored||id!=='study'))scrollTo(0,0)}
function openShelf(kind){S.shelf=kind;page('library');$('bibleShelf').hidden=kind!=='bible';$('egwShelf').hidden=kind!=='egw';document.querySelectorAll('[data-shelf]').forEach(x=>x.classList.toggle('active',x.dataset.shelf===kind));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.openShelf===kind));document.querySelector('.app')?.setAttribute('data-open-shelf',kind);if(kind==='egw')renderEgwBooks()}
async function loadData(){try{const u=['./data/egw-index.json','./data/egw-official-books.json','./data/bible-egw-relations.json','./data/bible-source.json','./data/bible-books.json'],r=await Promise.all(u.map(x=>fetch(x,{cache:'no-store'})));if(r.some(x=>!x.ok))throw Error();const[e,eb,rel,src,b]=await Promise.all(r.map(x=>x.json()));S.egw=e.records||[];S.egwBooks=eb.books||[];S.rels=rel.relations||[];S.source=src;S.books=b.books||[];$('status').textContent=`圣经 ${S.books.length} 卷 · 怀爱伦著作 ${S.egwBooks.length} 本`;migrate();home();library();renderProjects();renderBasket()}catch(e){console.error(e);$('status').textContent='资料加载失败，请刷新重试'}}
function parse(q){const n=norm(q);for(const[osis,full,short]of S.books)for(const a of[full,short]){const x=norm(a);if(n.startsWith(x)){const m=n.slice(x.length).match(/^(\d+)(?::(\d+)(?:-(\d+))?)?$/);if(m)return{osis,full,short,chapter:+m[1],from:m[2]?+m[2]:null,to:m[3]?+m[3]:(m[2]?+m[2]:null)}}}return null}
function parseAny(v){const a=parse(v);if(a)return a;for(const[osis,full,short]of S.books){const m=String(v||'').replace(/\s/g,'').match(new RegExp(`^${osis}(\\d+)(?::(\\d+)(?:-(\\d+))?)?$`,'i'));if(m)return{osis,full,short,chapter:+m[1],from:m[2]?+m[2]:null,to:m[3]?+m[3]:(m[2]?+m[2]:null)}}return null}
function overlap(a,b){if(!a||!b||a.osis!==b.osis||a.chapter!==b.chapter)return false;if(!a.from||!b.from)return true;return Math.max(a.from,b.from)<=Math.min(a.to||a.from,b.to||b.from)}
function relation(q){const n=norm(q),ref=parse(q),rows=S.rels.map(r=>{let s=0;for(const v of[r.bible_ref,r.normalized]){const x=norm(v);if(x===n)s=Math.max(s,140);else if(x.includes(n)||n.includes(x))s=Math.max(s,75);if(ref&&overlap(ref,parseAny(v)))s=Math.max(s,120)}for(const t of r.themes||[]){const x=norm(t);if(x===n)s=Math.max(s,110);else if(x.includes(n)||n.includes(x))s=Math.max(s,60)}return{r,s}}).filter(x=>x.s).sort((a,b)=>b.s-a.s).map(x=>x.r);return rows.length?{bible_ref:rows[0].bible_ref,themes:[...new Set(rows.flatMap(x=>x.themes||[]))],related:[...new Set(rows.flatMap(x=>x.related_bible||[]))],ids:[...new Set(rows.flatMap(x=>x.egw_ids||[]))]}:null}
function egwSearch(q,rel=relation(q)){const n=norm(q),ref=parse(q);return S.egw.map(e=>{let s=rel?.ids.includes(e.id)?180:0;if(ref){if((e.bible_refs||[]).some(v=>overlap(ref,parseAny(v))))s=Math.max(s,120)}else{[e.title_cn,e.chapter,e.locator,...(e.bible_refs||[]),...(e.topics||[])].forEach(v=>{const x=norm(v);if(x===n)s+=100;else if(n&&(x.includes(n)||n.includes(x)))s+=45});if(n&&norm(e.summary).includes(n))s+=15}return{e,s}}).filter(x=>x.s).sort((a,b)=>b.s-a.s).map(x=>x.e)}
function egwBookSearch(q){const n=norm(q),generic=['怀爱伦','怀著','怀师母','预言之灵','ellenwhite'].some(x=>n===norm(x)||n.includes(norm(x)));if(!n||generic)return [...S.egwBooks];return S.egwBooks.filter(b=>norm(b.title_cn).includes(n)||n.includes(norm(b.title_cn)))}
function egwBookCard(b){return`<article class="card" data-kind="egw"><div class="top"><span class="badge egw">怀爱伦著作</span><span class="title">《${esc(b.title_cn)}》</span></div><div class="snippet">官方中文书目，可直接打开目录选择章节阅读。</div><div class="actions"><button class="primary" data-official-url="${esc(b.toc_url)}" data-official-id="${b.id}">打开这本书</button></div></article>`}
async function book(osis){if(S.cache.has(osis))return S.cache.get(osis);const cfg=S.source?.translations?.[S.source.default_translation],r=await fetch(cfg.base_url+osis+'.json');if(!r.ok)throw Error();const j=await r.json();S.cache.set(osis,j);return j}
async function passage(ref){const b=await book(ref.osis),all=b.chapters?.[ref.chapter-1]?.verses||[];if(!all.length)throw Error();return{all,selected:ref.from?all.filter(v=>v.number>=ref.from&&v.number<=ref.to):all}}
const label=r=>`${r.full} ${r.chapter}${r.from?':'+r.from+(r.to!==r.from?'-'+r.to:''):'章'}`;
const itemId=x=>x.type==='bible'?`bible:${x.ref.osis}:${x.ref.chapter}`:x.native_url?`egw-native:${x.native_url}`:`egw:${x.book.id}`;
function remember(item){const a=read(K.reading).filter(x=>itemId(x)!==itemId(item));a.unshift({...item,at:Date.now()});write(K.reading,a.slice(0,12));home()}
function isFavorite(item){return read(K.favorites).some(x=>itemId(x)===itemId(item))}
function toggleFavorite(item){let a=read(K.favorites),id=itemId(item);if(a.some(x=>itemId(x)===id)){a=a.filter(x=>itemId(x)!==id);toast('已取消收藏')}else{a.unshift({...item,at:Date.now()});toast('已收藏')}write(K.favorites,a);home();renderFavorites()}
function historyCard(item,favorite=false){if(item.type==='bible')return`<button class="card historyCard" data-bible='${esc(JSON.stringify(item.ref))}'><span><span class="badge bible">圣经</span> <b>${esc(item.title)}</b></span><span>${favorite?'打开':'继续阅读 ›'}</span></button>`;if(item.native_url)return`<button class="card historyCard" data-egw-native-url="${esc(item.native_url)}" data-egw-title="${esc(item.title||'怀爱伦著作')}" data-egw-chapter="${esc(item.chapter||'')}"><span><span class="badge egw">怀爱伦</span> <b>${esc(item.title||'怀爱伦著作')}${item.chapter?` · ${esc(item.chapter)}`:''}</b></span><span>${favorite?'打开':'继续阅读 ›'}</span></button>`;return`<button class="card historyCard" data-official-url="${esc(item.book.toc_url)}" data-official-id="${item.book.id}"><span><span class="badge egw">怀爱伦</span> <b>《${esc(item.book.title_cn)}》</b></span><span>${favorite?'打开':'继续阅读 ›'}</span></button>`}
function bibleFont(delta=0){const size=Math.max(16,Math.min(28,+(localStorage.getItem(K.font)||19)+delta));localStorage.setItem(K.font,size);document.documentElement.style.setProperty('--reader-font',`${size}px`);return size}
function biblePositionSnapshot(){const d=$('detail'),verses=[...d.querySelectorAll('.reading>.verse')];if(!verses.length)return null;const y=(d.scrollTop||0)+Math.min(140,Math.max(72,d.clientHeight*.18));let i=verses.findIndex(v=>v.offsetTop+v.offsetHeight>y);if(i<0)i=verses.length-1;const v=verses[i],height=Math.max(1,v.offsetHeight);return{verse:+v.dataset.verse,index:i,offset:+Math.max(0,Math.min(1,(y-v.offsetTop)/height)).toFixed(3)}}
function markBiblePosition(saved){const d=$('detail');d.querySelectorAll('.readingMark').forEach(x=>x.classList.remove('readingMark'));if(!saved||typeof saved!=='object')return;const v=d.querySelector(`.reading>.verse[data-verse="${+saved.verse}"]`)||d.querySelectorAll('.reading>.verse')[+saved.index||0];v?.classList.add('readingMark')}
function saveReadingPosition(){const d=$('detail'),key=d?.dataset.readingKey;if(!key||d.dataset.readerKind!=='bible-reader')return;const snap=biblePositionSnapshot();if(!snap)return;const all=read(K.position,{});all[key]=snap;write(K.position,all);markBiblePosition(snap)}
let readingPositionTimer=0;function flushReadingPosition(){if(readingPositionTimer){clearTimeout(readingPositionTimer);readingPositionTimer=0}if($('detail').open)saveReadingPosition()}function scheduleReadingPosition(){if(!$('detail').open)return;if(readingPositionTimer)clearTimeout(readingPositionTimer);readingPositionTimer=setTimeout(()=>{readingPositionTimer=0;saveReadingPosition()},240)}
function restoreReadingPosition(key,focus){const d=$('detail');d.dataset.readingKey=key;requestAnimationFrame(()=>{const saved=read(K.position,{})[key];if(saved&&typeof saved==='object'){const verses=[...d.querySelectorAll('.reading>.verse')],v=d.querySelector(`.reading>.verse[data-verse="${+saved.verse}"]`)||verses[+saved.index||0];if(v){const offset=Math.max(0,Math.min(1,+saved.offset||0));d.scrollTop=Math.max(0,v.offsetTop+v.offsetHeight*offset-Math.min(140,Math.max(72,d.clientHeight*.18)));markBiblePosition(saved);return}}if(Number.isFinite(+saved))d.scrollTop=Math.max(0,+saved);else if(focus)d.querySelector(`[data-verse="${focus}"]`)?.scrollIntoView({block:'center'});else d.scrollTop=0})}
function applyTheme(value=localStorage.getItem(K.theme)||'paper'){const allowed=['paper','sepia','green','dark'],theme=allowed.includes(value)?value:'paper';document.documentElement.dataset.theme=theme;localStorage.setItem(K.theme,theme);if($('themeSelect'))$('themeSelect').value=theme}
async function topicVerses(q,limit=18){const needle=String(q||'').trim();if(!needle||parse(q))return[];const found=[];for(let i=0;i<S.books.length;i+=8){const group=S.books.slice(i,i+8),loaded=await Promise.allSettled(group.map(async([osis,full,short])=>({osis,full,short,data:await book(osis)})));for(const row of loaded){if(row.status!=='fulfilled')continue;const{osis,full,short,data}=row.value;for(const chapter of data.chapters||[])for(const v of chapter.verses||[])if(String(v.text||'').includes(needle)){const ref={osis,full,short,chapter:chapter.chapter,from:v.number,to:v.number};found.push({ref,text:v.text});if(found.length>=limit)return found}}}return found}
function egwCard(e){return`<article class="card" data-kind="egw" data-egw="${esc(e.id)}"><div class="top"><span class="badge egw">怀爱伦著作</span><span class="title">《${esc(e.title_cn||'未命名资料')}》${e.chapter?' · '+esc(e.chapter):''}</span></div><div class="snippet"><b>内容提示：</b>${esc(e.summary||'暂无')}</div><div class="meta"><b>原文位置：</b>${esc(e.locator||'定位待复核')}${e.bible_refs?.length?' · 相关经文：'+e.bible_refs.map(esc).join('、'):''}</div></article>`}
const recentQueries=()=>read(K.recent).filter(x=>x&&typeof x.q==='string'&&x.q.trim()).slice(0,8);
function renderRecentSearches(){const host=$('studyResults'),rows=recentQueries();host.innerHTML=rows.length?`<section class="card recentSearchesCard"><div class="top"><span class="badge bible">最近搜索</span><button class="linkLike" data-recent-clear>清空</button></div><div class="chips">${rows.map(x=>`<button data-recent-query="${esc(x.q)}">${esc(x.q)}</button>`).join('')}</div></section>`:'<div class="empty">输入关键词或经文，结果会按圣经和怀爱伦著作分开显示。</div>';saveStudyState({results:host.innerHTML,scrollY:window.scrollY||0})}
let searchSeq=0;
async function search(q){q=String(q||'').trim();page('study',{keepScroll:true});$('studyQ').value=q;if(!q){renderRecentSearches();return}scrollTo(0,0);const rec=recentQueries().filter(x=>norm(x.q)!==norm(q));rec.unshift({q,at:Date.now()});write(K.recent,rec.slice(0,8));const host=$('studyResults'),requestId=++searchSeq;host.innerHTML='<div class="empty">正在读取真实资料；同时搜索中文和合本、怀爱伦资料索引和全部中文著作书目…</div>';saveStudyState({query:q,results:host.innerHTML,scrollY:0});const ref=parse(q),rel=relation(q),hits=egwSearch(q,rel),bookHits=egwBookSearch(q);let p=null,bibleHits=[];try{if(ref)p=await passage(ref);else bibleHits=await topicVerses(q)}catch{}if(requestId!==searchSeq)return;let cards=[];if(ref&&p)cards.push(`<article class="card" data-kind="bible" data-bible='${esc(JSON.stringify(ref))}'><div class="top"><span class="badge bible">圣经</span><span class="title">${esc(label(ref))}</span></div><div class="snippet">${esc(p.selected.map(v=>v.text).join(' '))}</div><div class="meta">和合本（简体）· 点击查看上下文</div></article>`);else{bibleHits.forEach(x=>cards.push(`<article class="card" data-kind="bible" data-bible='${esc(JSON.stringify(x.ref))}'><div class="top"><span class="badge bible">圣经</span><span class="title">${esc(label(x.ref))}</span></div><div class="snippet">${esc(x.text)}</div><div class="meta">和合本（简体）· 点击查看上下文</div></article>`));if(!bibleHits.length&&rel)cards.push(`<article class="card" data-kind="bible" data-query="${esc(rel.bible_ref)}"><div class="top"><span class="badge bible">圣经</span><span class="title">${esc(rel.bible_ref)}</span></div><div class="snippet">点击查看圣经原文和上下文。</div></article>`)}if(cards.length)cards.unshift(`<h2 class="groupTitle" data-kind="bible">圣经中与“${esc(q)}”相关的经文</h2>`);if(bookHits.length){cards.push(`<h2 class="groupTitle" data-kind="egw">怀爱伦中文著作书目（${bookHits.length}）</h2>`);bookHits.forEach(b=>cards.push(egwBookCard(b)))}if(hits.length){cards.push(`<h2 class="groupTitle" data-kind="egw">怀爱伦资料索引中与“${esc(q)}”相关的内容</h2>`);hits.forEach(e=>cards.push(egwCard(e)))}if(rel?.related.length)cards.push(`<div class="card" data-kind="bible"><div class="top"><span class="badge bible">相关经文</span><span class="title">继续查考</span></div><div class="chips">${rel.related.map(x=>`<button data-query="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`);host.innerHTML=cards.length?cards.join(''):'<div class="empty">和合本正文、怀爱伦书目和真实索引中暂时没有匹配结果。系统不会编造内容。</div>';filter();saveStudyState({query:q,results:host.innerHTML,scrollY:0})}
function filter(){document.querySelectorAll('#studyResults [data-kind]').forEach(x=>x.hidden=S.filter!=='all'&&x.dataset.kind!==S.filter);saveStudyState({filter:S.filter,results:$('studyResults')?.innerHTML||''})}
const verse=(v,target=false)=>`<div class="verse${target?' target':''}" data-verse="${v.number}"><i>${v.number}</i><span>${esc(v.text)}</span></div>`;
async function bibleDetail(ref){saveReadingPosition();const p=await passage(ref),data=await book(ref.osis),candidate=relation(label(ref)),rel=candidate&&overlap(ref,parseAny(candidate.bible_ref))?candidate:null,hits=egwSearch(label(ref),rel).filter(e=>(e.bible_refs||[]).some(v=>overlap(ref,parseAny(v)))||rel?.ids?.includes(e.id)),full=!ref.from,a=ref.from?Math.max(1,ref.from-2):1,z=ref.to?Math.min(p.all.length,ref.to+2):p.all.length,context=p.all.filter(v=>v.number>=a&&v.number<=z),prev=ref.chapter>1?{...ref,chapter:ref.chapter-1,from:null,to:null,focus:null}:null,next=ref.chapter<data.chapters.length?{...ref,chapter:ref.chapter+1,from:null,to:null,focus:null}:null,item={type:'bible',title:`${ref.full} ${ref.chapter}章`,ref:{...ref,from:null,to:null,focus:null}},key=`bible:${ref.osis}:${ref.chapter}`;$('detail').dataset.readerKind=full?'bible-reader':'bible-detail';if(full)remember(item);$('detailType').textContent=full?`${ref.full} ${ref.chapter}章`:'圣经详情';$('detailBody').innerHTML=`${full?`<div class="readerNav">${prev?`<button data-bible='${esc(JSON.stringify(prev))}'>‹ 上一章</button>`:'<span></span>'}${next?`<button data-bible='${esc(JSON.stringify(next))}'>下一章 ›</button>`:'<span></span>'}</div>`:''}<span class="badge bible">经文</span><h1>${esc(label(ref))}</h1><div class="meta">和合本（简体）${full?' · 全章阅读':' · 上下文 '+esc(ref.full)+' '+ref.chapter+':'+a+'-'+z}</div><div class="reading">${p.selected.map(v=>verse(v,full&&ref.focus===v.number)).join('')}</div>${full?'':`<section class="detailSection"><h2>上下文</h2><div class="reading">${context.map(v=>verse(v,ref.from&&v.number>=ref.from&&v.number<=ref.to)).join('')}</div></section>${rel?.related.length?`<section class="detailSection"><h2>相关经文</h2><div class="chips">${rel.related.map(x=>`<button data-query="${esc(x)}">${esc(x)}</button>`).join('')}</div></section>`:''}<section class="detailSection"><h2>相关怀著（${hits.length}）</h2><div class="results">${hits.length?hits.map(egwCard).join(''):'<div class="empty">当前真实索引没有精确关联，不会用推测补写。</div>'}</div></section>`}`;$('detailActions').innerHTML=full?`<button data-favorite-bible='${esc(JSON.stringify(item.ref))}'>${isFavorite(item)?'★ 已收藏':'☆ 收藏本章'}</button>${next?`<button class="primary" data-bible='${esc(JSON.stringify(next))}'>下一章 ›</button>`:'<button disabled>最后一章</button>'}`:`<button data-add-bible='${esc(JSON.stringify(ref))}'>加入材料篮</button><button class="primary" data-bible='${esc(JSON.stringify({...ref,focus:ref.from,from:null,to:null}))}'>阅读整章</button>`;openDetail();window.jgRefreshReadAloud?.();if(full)restoreReadingPosition(key,ref.focus);else{$('detail').dataset.readingKey='';requestAnimationFrame(()=>$('detail').querySelector('.verse.target')?.scrollIntoView({block:'center'}))}}
function egwDetail(id){const e=S.egw.find(x=>x.id===id);if(!e)return;$('detail').dataset.readerKind='egw-index-detail';$('detailType').textContent='预言之灵资料';$('detailBody').innerHTML=`<span class="badge egw">怀著</span><h1>《${esc(e.title_cn||'未命名资料')}》</h1><div class="meta">${esc(e.chapter||'章节未标注')} · ${esc(e.locator||'定位待复核')}</div><section class="detailSection"><h2>研究摘要</h2><div class="source">${esc(e.summary||'暂无')}<br><b>此处是研究摘要，不是怀爱伦原文。</b></div></section><section class="detailSection"><h2>相关经文</h2><div class="chips">${(e.bible_refs||[]).map(x=>`<button data-query="${esc(x)}">${esc(x)}</button>`).join('')||'暂无'}</div></section>`;const official=/^https:\/\/(m\.|text\.)?egwwritings\.org\//i.test(e.source_url||'')?e.source_url:'';$('detailActions').innerHTML=`<button data-add-egw="${esc(e.id)}">加入材料篮</button>${official?`<button class="primary" data-official-url="${esc(official)}">在救赎的历史内阅读原始出处</button>`:'<button disabled>暂无官方链接</button>'}`;openDetail();window.jgRefreshReadAloud?.()}
function openDetail(){if(!$('detail').open)$('detail').showModal()}function closeDetail(){saveReadingPosition();if($('detail').open)$('detail').close()}
function migrate(){write(K.basket,read(K.basket).map(x=>typeof x==='string'?{type:'egw',source_id:x}:x))}
function addEgw(id){const e=S.egw.find(x=>x.id===id),a=read(K.basket);if(e&&!a.some(x=>x.type==='egw'&&x.source_id===id))a.push({type:'egw',source_id:id,label:`《${e.title_cn}》 ${e.chapter||''}`,summary:e.summary,locator:e.locator,source_url:e.source_url,bible_refs:e.bible_refs||[]});write(K.basket,a);renderBasket();toast('已加入材料篮')}
async function addBible(ref){const p=await passage(ref),id=`${ref.osis}-${ref.chapter}-${ref.from||'all'}-${ref.to||'all'}`,a=read(K.basket);if(!a.some(x=>x.type==='bible'&&x.source_id===id))a.push({type:'bible',source_id:id,label:label(ref),text:p.selected.map(v=>`${v.number} ${v.text}`).join(' '),ref});write(K.basket,a);renderBasket();toast('经文已加入材料篮')}
function renderBasket(){const a=read(K.basket);$('basketCount').textContent=`${a.length} 条`;$('basketResults').innerHTML=a.length?a.map((x,i)=>`<article class="card"><div class="top"><span class="badge ${x.type}">${x.type==='bible'?'经文':'怀著'}</span><span class="title">${esc(x.label||x.source_id)}</span></div><div class="snippet">${esc(x.text||x.summary||'')}</div><div class="meta">${esc(x.locator||'')}</div><div class="actions"><button data-remove="${i}">移除</button><button ${x.type==='bible'?`data-bible='${esc(JSON.stringify(x.ref))}'`:`data-egw="${esc(x.source_id)}"`}>查看</button></div></article>`).join(''):'<div class="empty">材料篮还是空的。可从经文或怀著详情加入。</div>'}
const projects=()=>read(K.projects).map(x=>({status:'researching',audience:'普通信徒',duration_minutes:30,materials:[],research_notes:'',...x}));
function saveProjects(a){write(K.projects,a);renderProjects();home()}function createProject(){const t=$('projectTitle').value.trim();if(!t)return;const a=projects(),now=new Date().toISOString();a.unshift({id:`sermon-${Date.now()}`,title:t,status:'researching',audience:$('audience').value,duration_minutes:+$('duration').value,materials:[],research_notes:'',created_at:now,updated_at:now});saveProjects(a);$('projectForm').reset();toast('讲章已建立')}
function attach(id){const a=projects(),p=a.find(x=>String(x.id)===String(id)),seen=new Set(p.materials.map(x=>`${x.type}:${x.source_id}`));read(K.basket).forEach(x=>{const k=`${x.type}:${x.source_id}`;if(!seen.has(k)){p.materials.push({...x});seen.add(k)}});saveProjects(a);toast('材料篮已加入讲章')}
function renderProjects(){const a=projects();$('projectsList').innerHTML=a.length?a.map(p=>`<article class="card form"><div class="top"><span class="badge bible">研究中</span><span class="title">${esc(p.title)}</span></div><div class="meta">${esc(p.audience)} · ${p.duration_minutes}分钟 · ${p.materials.length} 条材料</div><label>我的研究笔记<textarea data-notes="${esc(p.id)}">${esc(p.research_notes)}</textarea></label><div class="actions"><button class="primary" data-attach="${esc(p.id)}">把材料篮加入讲章</button></div></article>`).join(''):'<div class="empty">还没有讲章项目。填写讲题即可建立。</div>'}
function home(){const r=read(K.reading).slice(0,4),f=read(K.favorites).slice(0,4);$('recentReading').innerHTML=r.length?r.map(x=>historyCard(x)).join(''):'<div class="empty">打开圣经章节或怀爱伦著作后，会自动显示在这里。</div>';const fp=$('favoritePreview');if(fp){if(f.length){fp.hidden=false;fp.setAttribute('aria-hidden','false');fp.innerHTML='<h2>我的收藏</h2>'+f.map(x=>historyCard(x,true)).join('')}else{fp.hidden=true;fp.setAttribute('aria-hidden','true');fp.innerHTML=''}}}
function renderFavorites(){const a=read(K.favorites);$('favoritesList').innerHTML=a.length?a.map(x=>`${historyCard(x,true)}<div class="actions"><button data-unfavorite="${esc(itemId(x))}">取消收藏</button></div>`).join(''):'<div class="empty">还没有收藏。打开一本书或圣经章节，点击“收藏”。</div>'}
function renderBibleBooks(){const q=norm($('bibleBookSearch').value),rows=q?S.books.filter(x=>norm(x[1]).includes(q)||norm(x[2]).includes(q)):S.books,group=(title,a)=>`<h2 class="shelfGroup">${title}</h2><div class="bookGrid">${a.map(([osis,full])=>`<button data-book="${esc(osis)}">${esc(full)}</button>`).join('')}</div>`;$('bibleBooks').innerHTML=rows.length?(q?group(`找到 ${rows.length} 卷`,rows):group('旧约 · 39卷',rows.slice(0,39))+group('新约 · 27卷',rows.slice(39))):'<div class="empty">没有找到这个书名。</div>'}
function renderEgwBooks(){const input=$('egwBookSearch'),host=$('egwBooks');if(!input||!host||host.classList.contains('egwNativeList'))return;const q=norm(input.value),rows=q?egwBookSearch(q):[...S.egwBooks],count=$('egwBookCount');if(count)count.textContent=q?`找到 ${rows.length} 本 · 共 ${S.egwBooks.length} 本`:`${S.egwBooks.length} 本`;host.innerHTML=rows.length?`<h2 class="wide shelfGroup">${q?'搜索结果':'全部著作'} · ${rows.length} 本</h2>${rows.map(b=>`<button data-official-url="${esc(b.toc_url)}" data-official-id="${b.id}"><b>《${esc(b.title_cn)}》</b><span>打开目录并选择章节</span></button>`).join('')}`:'<div class="empty">没有找到这个书名。</div>'}
function library(){if($('bibleBookSearch'))renderBibleBooks();if($('egwBookSearch'))renderEgwBooks()}
async function openBook(osis){const meta=S.books.find(x=>x[0]===osis),data=await book(osis);$('bibleShelf').innerHTML=`<button class="chip" data-books>‹ 返回书卷</button><h2>${esc(meta[1])} · 选择章节</h2><div class="bibleChapterList">${data.chapters.map(c=>`<button class="bibleChapterRow" data-bible='${esc(JSON.stringify({osis,full:meta[1],short:meta[2],chapter:c.chapter,from:null,to:null}))}'><span>第${String(c.chapter).padStart(2,'0')}章</span><b>›</b></button>`).join('')}</div>`}
function renderBookShelf(){$('bibleShelf').innerHTML='<h2>圣经 · 和合本简体</h2><input id="bibleBookSearch" placeholder="输入书名，例如：约翰福音、诗篇"><div id="bibleBooks"></div>';$('bibleBookSearch').addEventListener('input',debounce(renderBibleBooks,250));renderBibleBooks()}
document.addEventListener('click',async e=>{const pageBtn=e.target.closest('[data-page]');if(pageBtn){e.preventDefault();page(pageBtn.dataset.page);return}const shelfBtn=e.target.closest('[data-open-shelf]');if(shelfBtn){e.preventDefault();openShelf(shelfBtn.dataset.openShelf);return}const recentClear=e.target.closest('[data-recent-clear]');if(recentClear){write(K.recent,[]);renderRecentSearches();return}const recent=e.target.closest('[data-recent-query]');if(recent){await search(recent.dataset.recentQuery);return}const favBible=e.target.closest('[data-favorite-bible]');if(favBible){const ref=JSON.parse(favBible.dataset.favoriteBible),item={type:'bible',title:`${ref.full} ${ref.chapter}章`,ref};toggleFavorite(item);favBible.textContent=isFavorite(item)?'★ 已收藏':'☆ 收藏本章';return}const unfav=e.target.closest('[data-unfavorite]');if(unfav){write(K.favorites,read(K.favorites).filter(x=>itemId(x)!==unfav.dataset.unfavorite));renderFavorites();home();toast('已取消收藏');return}const bk=e.target.closest('[data-book]');if(bk){await openBook(bk.dataset.book);return}if(e.target.closest('[data-books]')){renderBookShelf();return}const q=e.target.closest('[data-query]');if(q){closeDetail();await search(q.dataset.query);return}const b=e.target.closest('[data-bible]');if(b){if($('study').classList.contains('active'))saveStudyState({results:$('studyResults').innerHTML,scrollY:window.scrollY||0});try{await bibleDetail(JSON.parse(b.dataset.bible))}catch{toast('中文圣经正文暂时读取失败')}return}const g=e.target.closest('[data-egw]');if(g){if($('study').classList.contains('active'))saveStudyState({results:$('studyResults').innerHTML,scrollY:window.scrollY||0});egwDetail(g.dataset.egw);return}const ab=e.target.closest('[data-add-bible]');if(ab){await addBible(JSON.parse(ab.dataset.addBible));return}const ag=e.target.closest('[data-add-egw]');if(ag){addEgw(ag.dataset.addEgw);return}const rm=e.target.closest('[data-remove]');if(rm){const a=read(K.basket);a.splice(+rm.dataset.remove,1);write(K.basket,a);renderBasket();return}const at=e.target.closest('[data-attach]');if(at)attach(at.dataset.attach)});
window.jgAppNavigationReady=true;
document.querySelector('.fontTools').addEventListener('click',e=>{const b=e.target.closest('[data-font]');if(!b)return;const d=$('detail');const keep=d.open&&d.dataset.readerKind==='bible-reader'?biblePositionSnapshot():null;bibleFont(+b.dataset.font);if(keep)requestAnimationFrame(()=>{const verses=[...d.querySelectorAll('.reading>.verse')],v=d.querySelector(`.reading>.verse[data-verse="${+keep.verse}"]`)||verses[+keep.index||0];if(!v)return;const offset=Math.max(0,Math.min(1,+keep.offset||0));d.scrollTop=Math.max(0,v.offsetTop+v.offsetHeight*offset-Math.min(140,Math.max(72,d.clientHeight*.18)));markBiblePosition(keep)})});$('detail').addEventListener('scroll',scheduleReadingPosition,{passive:true});$('detail').addEventListener('cancel',flushReadingPosition);$('detail').addEventListener('close',flushReadingPosition);window.addEventListener('pagehide',flushReadingPosition);document.addEventListener('visibilitychange',()=>{if(document.hidden)flushReadingPosition()});
const runStudySearchDebounced=debounce(()=>search($('studyQ')?.value||''),250),runBibleShelfSearchDebounced=debounce(renderBibleBooks,250),runEgwShelfSearchDebounced=debounce(renderEgwBooks,250);let studyComposing=false;const studyInput=$('studyQ');studyInput?.addEventListener('compositionstart',()=>{studyComposing=true;runStudySearchDebounced.cancel()});studyInput?.addEventListener('compositionend',()=>{studyComposing=false;if(!String(studyInput.value||'').trim())renderRecentSearches();else runStudySearchDebounced()});studyInput?.addEventListener('input',()=>{if(studyComposing)return;if(!String(studyInput.value||'').trim()){runStudySearchDebounced.cancel();renderRecentSearches();return}runStudySearchDebounced()});
document.querySelectorAll('[data-search]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const isStudy=f.contains($('studyQ'));if(isStudy)runStudySearchDebounced.cancel();search(new FormData(f).get('q'))}));$('projectForm').addEventListener('submit',e=>{e.preventDefault();createProject()});$('back').onclick=()=>{closeDetail();if($('study').classList.contains('active')){const saved=readStudyState();if(saved&&Number.isFinite(+saved.scrollY))requestAnimationFrame(()=>scrollTo(0,Math.max(0,+saved.scrollY||0)))}};window.addEventListener('scroll',()=>{if($('study').classList.contains('active'))saveStudyState({results:$('studyResults')?.innerHTML||'',scrollY:window.scrollY||0})},{passive:true});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));filter()});$('bibleBookSearch').addEventListener('input',runBibleShelfSearchDebounced);$('egwBookSearch').addEventListener('input',runEgwShelfSearchDebounced);$('themeSelect').addEventListener('change',e=>applyTheme(e.target.value));$('projectsList').addEventListener('change',e=>{if(e.target.dataset.notes){const a=projects(),p=a.find(x=>String(x.id)===e.target.dataset.notes);p.research_notes=e.target.value;p.updated_at=new Date().toISOString();write(K.projects,a);home()}});applyTheme();bibleFont();loadData();
