(() => {
  const $=id=>document.getElementById(id);
  const safe=s=>esc(String(s??''));
  let books=[];
  async function loadBooks(){if(books.length)return books;try{const r=await fetch('./data/egw-books.json',{cache:'no-store'});if(r.ok)books=(await r.json()).books||[]}catch(e){console.warn(e)}return books}
  function countForBook(b){return (egw||[]).filter(e=>String(e.book_code||'').toLowerCase().startsWith(String(b.code||'').toLowerCase())||String(e.title_cn||'')===String(b.title_cn||'')).length}
  function cards(rows){return rows.length?rows.map(egwCard).join(''):'<div class="empty">当前本地已核验出处还没有这一项。可以打开官方中文资料继续核对；经光不会补写或猜测原文。</div>'}
  window.jgBrowseEGWCategory=async cat=>{await loadBooks();const host=$('egwLibraryResults');if(!host)return;const bs=books.filter(b=>b.category===cat),names=new Set(bs.map(b=>b.title_cn)),codes=bs.map(b=>String(b.code||'').toLowerCase());const rows=(egw||[]).filter(e=>names.has(e.title_cn)||codes.some(c=>String(e.book_code||'').toLowerCase().startsWith(c)));host.innerHTML=`<div class="card"><div class="meta">${safe(cat)}</div><div class="chips">${bs.map(b=>`<button class="chip" onclick="window.jgBrowseEGWBook('${safe(b.code)}')">${safe(b.title_cn)} · ${countForBook(b)}</button>`).join('')}</div></div>${cards(rows)}`};
  window.jgBrowseEGWBook=async code=>{await loadBooks();const b=books.find(x=>String(x.code)===String(code));if(!b)return;const rows=(egw||[]).filter(e=>String(e.book_code||'').toLowerCase().startsWith(String(code).toLowerCase())||String(e.title_cn||'')===String(b.title_cn));const host=$('egwLibraryResults');if(host)host.innerHTML=`<div class="card"><div class="meta">书目</div><h3>《${safe(b.title_cn)}》</h3><p>${safe(b.category)} · 本地已核验 ${rows.length} 条出处</p><div class="actions"><button onclick="window.jgOpenOfficialEGW()">官方中文资料</button></div></div>${cards(rows)}`};
  const baseRender=renderLibrary;
  renderLibrary=async function(){await baseRender();await loadBooks();const host=$('libraryList');if(!host||$('jgEgwBrowser'))return;const cats=[...new Set(books.map(b=>b.category).filter(Boolean))];const coverage=books.map(b=>({b,n:countForBook(b)}));const indexed=coverage.filter(x=>x.n>0).length;const box=document.createElement('div');box.id='jgEgwBrowser';box.className='card';box.style.marginTop='12px';box.innerHTML=`<div class="meta">中文书目导航</div><h3>按书目和类别浏览</h3><p class="muted">${books.length} 本中文书目 · ${indexed} 本已有本地核验出处。书目目录不存受版权保护全文。</p><div class="chips">${cats.map(c=>`<button class="chip" onclick="window.jgBrowseEGWCategory('${safe(c)}')">${safe(c)}</button>`).join('')}</div><div class="section-head" style="margin-top:14px"><h2>书目</h2><span>数字=本地已核验出处数</span></div><div class="egw-book-grid">${coverage.map(x=>`<button onclick="window.jgBrowseEGWBook('${safe(x.b.code)}')"><b>${safe(x.b.title_cn)}</b><span>${safe(x.b.category)} · ${x.n}</span></button>`).join('')}</div>`;const result=$('egwLibraryResults');host.insertBefore(box,result||host.firstChild)};
  const s=document.createElement('style');s.textContent=`.egw-book-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.egw-book-grid button{border:1px solid var(--line);background:#0d192b;color:#fff;border-radius:12px;padding:10px;text-align:left}.egw-book-grid b{display:block;font-size:12px}.egw-book-grid span{display:block;color:var(--muted);font-size:10px;margin-top:3px}@media(min-width:700px){.egw-book-grid{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(s);
})();
